# Generated by Django 4.0 on 2026-02-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='manager',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chores.manager'),
        ),
    ]
