# Generated by Django 4.0 on 2026-02-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.chore')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='chores',
            field=models.ManyToManyField(related_name='days', through='chores.ChoreAssignment', to='chores.Chore'),
        ),
        migrations.AddField(
            model_name='choreassignment',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.day'),
        ),
        migrations.AddConstraint(
            model_name='choreassignment',
            constraint=models.UniqueConstraint(fields=('chore', 'day'), name='unique_chore_in_day'),
        ),
    ]
