# Generated by Django 4.0 on 2026-02-14 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_alter_chore_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chore',
            name='manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chores.manager'),
        ),
        migrations.AlterField(
            model_name='day',
            name='chore',
            field=models.ManyToManyField(blank=True, to='chores.Chore'),
        ),
    ]
