# Generated by Django 4.0 on 2026-02-14 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_alter_chore_category_alter_chore_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='chore',
            new_name='chores',
        ),
        migrations.AlterField(
            model_name='chore',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chores.manager'),
        ),
    ]
