# Generated by Django 4.0 on 2026-02-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_rename_chore_day_chores_alter_chore_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='chores',
            field=models.ManyToManyField(blank=True, default=None, to='chores.Chore'),
        ),
    ]
